# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nchat.proto\"\x15\n\x13ListMessagesRequest\"2\n\x14ListMessagesResponse\x12\x1a\n\x08messages\x18\x01 \x03(\x0b\x32\x08.Message\"\'\n\x14\x43reateMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"&\n\x07Message\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2y\n\x04\x43hat\x12=\n\x0cListMessages\x12\x14.ListMessagesRequest\x1a\x15.ListMessagesResponse\"\x00\x12\x32\n\rCreateMessage\x12\x15.CreateMessageRequest\x1a\x08.Message\"\x00\x62\x06proto3')
)




_LISTMESSAGESREQUEST = _descriptor.Descriptor(
  name='ListMessagesRequest',
  full_name='ListMessagesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=35,
)


_LISTMESSAGESRESPONSE = _descriptor.Descriptor(
  name='ListMessagesResponse',
  full_name='ListMessagesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messages', full_name='ListMessagesResponse.messages', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=87,
)


_CREATEMESSAGEREQUEST = _descriptor.Descriptor(
  name='CreateMessageRequest',
  full_name='CreateMessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='CreateMessageRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=128,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Message.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='Message.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=168,
)

_LISTMESSAGESRESPONSE.fields_by_name['messages'].message_type = _MESSAGE
DESCRIPTOR.message_types_by_name['ListMessagesRequest'] = _LISTMESSAGESREQUEST
DESCRIPTOR.message_types_by_name['ListMessagesResponse'] = _LISTMESSAGESRESPONSE
DESCRIPTOR.message_types_by_name['CreateMessageRequest'] = _CREATEMESSAGEREQUEST
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListMessagesRequest = _reflection.GeneratedProtocolMessageType('ListMessagesRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTMESSAGESREQUEST,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:ListMessagesRequest)
  ))
_sym_db.RegisterMessage(ListMessagesRequest)

ListMessagesResponse = _reflection.GeneratedProtocolMessageType('ListMessagesResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTMESSAGESRESPONSE,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:ListMessagesResponse)
  ))
_sym_db.RegisterMessage(ListMessagesResponse)

CreateMessageRequest = _reflection.GeneratedProtocolMessageType('CreateMessageRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEMESSAGEREQUEST,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:CreateMessageRequest)
  ))
_sym_db.RegisterMessage(CreateMessageRequest)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  ))
_sym_db.RegisterMessage(Message)



_CHAT = _descriptor.ServiceDescriptor(
  name='Chat',
  full_name='Chat',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=170,
  serialized_end=291,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListMessages',
    full_name='Chat.ListMessages',
    index=0,
    containing_service=None,
    input_type=_LISTMESSAGESREQUEST,
    output_type=_LISTMESSAGESRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateMessage',
    full_name='Chat.CreateMessage',
    index=1,
    containing_service=None,
    input_type=_CREATEMESSAGEREQUEST,
    output_type=_MESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHAT)

DESCRIPTOR.services_by_name['Chat'] = _CHAT

# @@protoc_insertion_point(module_scope)
