# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chat_pb2 as chat__pb2


class ChatStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListMessages = channel.unary_unary(
        '/Chat/ListMessages',
        request_serializer=chat__pb2.ListMessagesRequest.SerializeToString,
        response_deserializer=chat__pb2.ListMessagesResponse.FromString,
        )
    self.CreateMessage = channel.unary_unary(
        '/Chat/CreateMessage',
        request_serializer=chat__pb2.CreateMessageRequest.SerializeToString,
        response_deserializer=chat__pb2.Message.FromString,
        )


class ChatServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListMessages(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChatServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListMessages': grpc.unary_unary_rpc_method_handler(
          servicer.ListMessages,
          request_deserializer=chat__pb2.ListMessagesRequest.FromString,
          response_serializer=chat__pb2.ListMessagesResponse.SerializeToString,
      ),
      'CreateMessage': grpc.unary_unary_rpc_method_handler(
          servicer.CreateMessage,
          request_deserializer=chat__pb2.CreateMessageRequest.FromString,
          response_serializer=chat__pb2.Message.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Chat', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
